name: 42-notify-dev
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - RECIPIENT_EMAILS=${RECIPIENT_EMAILS}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    volumes:
      - .:/usr/src/app # This line mounts the current directory into the container
      - ./logs:/tmp/logs # This line mounts the logs directory into the container
      - /usr/src/app/node_modules # This line puts node_modules in an anonymous volume so that it is not overwritten by the mounted directory